### ISSUE TITLE
Mesh-Task Creating Roles

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-aws-consul-ecs#111]
The the roles variables state they will create a role if none is provided, it seems roles for cloudwatch "create log group" are still being created.

In many areas and business there is governance on IAM role creation and as such, no roles should be created at all if iam role ARNs are already provided.

**Comment by pglass** [comment]
Hi @reskin89, thanks for the issue!

It looks like we were missing a count variable here to conditionally create the execution role: https://github.com/hashicorp/terraform-aws-consul-ecs/blob/e5f04ed13da7f8aee7288fdb7443288024196223/modules/mesh-task/iam.tf#L110-L111

This should be fixed in https://github.com/hashicorp/terraform-aws-consul-ecs/pull/113, which will be part of our next release (v0.5).

*NOTE*: To address another issue with passing in existing roles, you'll need to set `create_task_role=false` and `create_execution_role=false` as well in the next release (v0.5).
