### ISSUE TITLE
Question: Is this Consul Connect?

### ISSUE THREAD

**Issue by oliveirafilipe** [hashicorp/terraform-aws-consul-ecs#15]
Hey Folks! Hope this issue finds you all well! :smile: 

I found this repo at [Consul's Docs Page](https://www.consul.io/docs). 

I became interested in the consul because of its Service Mesh capability.

In the [Service Mesh overview documentation page](https://www.consul.io/docs/connect) and in this another example repository [aws-samples/amazon-ecs-fargate-consul-connect-example](https://github.com/aws-samples/amazon-ecs-fargate-consul-connect-example), they talk about "Consult Connect", as if "Connect" were a specific service/functionality.

But I couldn't find any mention of "Connect" here in this repository, although I believe the purpose is the same.

Just to be sure: does this repository implement a "Consul Connect" example? Is "Connect" still a thing?

**Comment by lkysow** [comment]
Hi Filipe,
Yes this is for Consul Connect support!

We're trying to move away from the term "Consul Connect" and use "Consul" or "Consul Service Mesh" because we think it better explains the functionality so that's why there's no mention of it here but we should probably still add something about it to avoid confusion.

**Comment by oliveirafilipe** [comment]
Thanks for the super-quick reply! :rocket:
