### ISSUE TITLE
Default security group for the ecs service may not allow access from created load balancer

### ISSUE THREAD

**Issue by ShyWiz** [hashicorp/terraform-aws-consul-ecs#74]
This is for the dev-server module of this project.

By default, the security group attached to the ECS service (in this case the consul server), is the default security group of the VPC used ([reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#network_configuration)).

Currently, this option is not configurable in this module (check [main.tf](https://github.com/hashicorp/terraform-aws-consul-ecs/blob/main/modules/dev-server/main.tf) line 66).

If the default security group of the VPC used does not permit the IP addresses used by the load balancer (as what happened in my case) then you won't be able to connect to the Consul UI via the load balancer.

**Comment by ShyWiz** [comment]
#75

**Comment by pglass** [comment]
Hi @ShyWiz! Thanks for the issue and PR!

We did want to emphasize that the dev-server module is _not_ suitable for production use, so in general we don't intend to add features or improvements to the dev-server module beyond our needs for testing or examples.

That said, we'll be merging in your PR shortly since it allows testing with the dev-server existing VPCs 🙂
